email: dansebcar@gmail.com

defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: Dan Carpenter
      description:
        I'm Dan Carpenter, a full-stack web developer working for testXchange GmbH in Berlin, Germany. My favourite tools are Django, Postgres and Vue.
      hero: false
      css:

url: https://dansebcar.github.io/
github_username:  dansebcar

markdown: kramdown

exclude:
  - node_modules

kramdown:
  input: GFM
  syntax_highlighter: pygments
