email: dansebcar@gmail.com

defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: Dan Carpenter
      description:
        I'm Dan Carpenter, a full-stack web developer working for testXchange GmbH in Berlin, Germany. My favourite tools are Django, Postgres and Vue.
      hero: false
      css:

url: https://dansebcar.github.io/
github_username:  dansebcar

markdown: kramdown
theme: null

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - assets/src
  - assets/*.config.js

kramdown:
  input: GFM
  syntax_highlighter: pygments
