version: '3'
services:
    web:
        image: jekyll/jekyll
        command: jekyll serve
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
    assets:
        build: .
        command: npm run watch
        volumes:
            - ./assets:/code/assets
        environment:
            - NODE_ENV=development
